services:
  
  app:
    
    build:
      context: .
      dockerfile: Dockerfile

    container_name: catalogo_jogos_api
    environment:
          - DB_USERNAME=postgres
          - DB_PASSWORD=InfraAWS_2025
          - DB_DATABASE=catalogo_jogos
          - DB_HOST=aws-db.c1dzzl7szzye.us-east-1.rds.amazonaws.com

    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start"]