services:
  
  app:
    
    build:
      context: .
      dockerfile: Dockerfile

    container_name: catalogo_jogos_api
    environment:
          - DB_USERNAME=postgres
          - DB_PASSWORD=Rocket-Racoon1
          - DB_DATABASE=db-victor-soares
          - DB_HOST=db-victor-soares.c1dzzl7szzye.us-east-1.rds.amazonaws.com

    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start"]
