services:
  app:
    build: .
    container_name: catalogo_jogos_api
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=catalogo_jogos
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start"]
    networks:
      - game_catalog

  db:
    image: postgres:latest
    container_name: catalogo_jogos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogo_jogos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - game_catalog

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - game_catalog

volumes:
  pgdata:

networks:
  game_catalog:
    driver: bridge
